#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by bootstrap.py. Please use
# bootstrap.py to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -euv

cd $GITHUB_WORKSPACE/../pulp-openapi-generator
COMMIT_MSG=$(git log --format=%B --no-merges -1)
export PULP_BINDINGS_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulp-openapi-generator\/pull\/(\d+)' | awk -F'/' '{print $7}')

if [ -n "$PULP_BINDINGS_PR_NUMBER" ]; then
  git fetch origin pull/$PULP_BINDINGS_PR_NUMBER/head:$PULP_BINDINGS_PR_NUMBER
  git checkout $PULP_BINDINGS_PR_NUMBER
fi

./generate.sh pulpcore ruby 0
cd pulpcore-client
gem build pulpcore_client
gem install --both ./pulpcore_client-0.gem
cd ..

./generate.sh pulp_npm ruby 0

cd pulp_npm-client
gem build pulp_npm_client
gem install --both ./pulp_npm_client-0.gem

rm -rf ./pulpcore-client
rm -rf ./pulp_npm-client

echo "---
:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
sudo chmod 600 ~/.gem/credentials

cd $GITHUB_WORKSPACE
export REPORTED_VERSION=$(http :24817/pulp/api/v3/status/ | jq --arg plugin pulp_npm -r '.versions[] | select(.component == $plugin) | .version')
export DESCRIPTION="$(git describe --all --exact-match `git rev-parse HEAD`)"
if [[ $DESCRIPTION == 'tags/'$REPORTED_VERSION ]]; then
  export VERSION=${REPORTED_VERSION}
else
  # Daily publishing of development version (ends in ".dev" reported as ".dev0")
  if [ "${REPORTED_VERSION%.dev*}" == "${REPORTED_VERSION}" ]; then
    echo "Refusing to publish bindings. $REPORTED_VERSION does not contain 'dev'."
    exit 1
  fi
  export EPOCH="$(date +%s)"
  export VERSION=${REPORTED_VERSION}${EPOCH}
fi

export response=$(curl --write-out %{http_code} --silent --output /dev/null https://rubygems.org/gems/pulp_npm_client/versions/$VERSION)

if [ "$response" == "200" ];
then
  exit
fi

cd ../pulp-openapi-generator

./generate.sh pulp_npm ruby $VERSION
cd pulp_npm-client
gem build pulp_npm_client
GEM_FILE="$(ls | grep pulp_npm_client-)"
gem push ${GEM_FILE}
