# Generated by Django 2.2.19 on 2021-02-23 18:05

from django.db import migrations


def migrate_distribution_fields(apps, schema_editor):
    # Set the core "_repository" and "_repository_version" fields on the core table with the values
    # from the child table.
    NpmDistribution = apps.get_model('npm', 'npmdistribution')

    distributions = list(NpmDistribution.objects.all())

    for distribution in distributions:
        distribution._repository = distribution.repository
        distribution._repository_version = distribution.repository_version

    NpmDistribution.objects.bulk_update(distributions, ['_repository', '_repository_version'])


class Migration(migrations.Migration):

    dependencies = [
        ('npm', '0001_initial'),
        ('core', '0060_add_new_distribution_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_distribution_fields),
        migrations.RemoveField(
            model_name='npmdistribution',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='npmdistribution',
            name='repository_version',
        ),
    ]
