# Generated by Django 4.2.19 on 2025-02-11 21:03

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_add_domain'),
        ('npm', '0003_alter_npmdistribution_distribution_ptr_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='package',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'version', '_pulp_domain')},
        ),
    ]
