# Generated by Django 4.2.28 on 2026-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npm', '0004_alter_package_unique_together_package__pulp_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(max_length=256),
        ),
    ]
